baseurl: "https://kotlinconf-brasil.netlify.com/"
title: "KotlinConf 2019 Global Curitiba"
canonifyurls: true
theme: "hugo-conference-kotlin-cwb-2019"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "KotlinConf 2019 Global - Curitiba"
  Description: "1ª conferência de Kotlin no Brasil"
  Date: "25 de Janeiro de 2020"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "na Contabilizei"
  Address: "Boulevard Kukulcan, 30"
  City:  "em Curitiba"
  State: "Quintana"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"
  whoami: > 
    A KotlinConf de Copenhagen ganha sua versão brasileira em Curitiba! 

    Através do movimento KotlinConf 2019 Global, teremos um dia inteiro de imersão na linguagem e seu ecossistema em um ambiente perfeito para a troca de ideias e aprendizado.
    
    Compareça, é grátis!

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    # - location
    - speakers
    - schedule
    - sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "C4P"
    location: "Location"
    speakers: "Palestrantes"
    schedule: "Agenda"
    sponsors: "Patrocinadores"
    partners: "Parceiros"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Cadastre-se!"
    link: "https://www.meetup.com/KotlinCWB/events/265941182/"
  C4P:
    buttontext: "Inscreva-se para palestrar"
    link: "https://sessionize.com/kotlin-conf-2019-curitiba/"
    text: "oee kakaka"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Jetbrains"
      logo: "/img/jetbrains.svg"
      url: "https://www.jetbrains.com"

  # List of Partners
  Partners:
    - name: "Contabilizei"
      logo: "/img/contabilizei.png"
      url: "https://www.contabilizei.com.br"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Check-in / Breakfast"
      time: "9h00"

    - name: "Linus Torvalds"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Linux Foundation"
      link:
        href: "http://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Digging into a Linux Kernel"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"

    - name: "Bill Gates"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Microsoft"
      link:
        href: "http://github.com/billy95"
        text: "@billy95"
      presentation:
        title: "Introducing Windows 12"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "11h00"

    - name: "Lunch"
      time: "12h00"

    - name: "Chuck Norris"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

    - name: "Steve Jobs"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "14h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Mark Zuckerberg"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "Steve Wozniak"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Why do I prefer Android over iPhone"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"
